name: PHPStan
on:
  workflow_dispatch:
jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: php-actions/phpstan@v3
        with:
          path: src/
          level: 5
